### ISSUE TITLE
You should set 'COOKIE' in 'Config.conf' file for the Claude or login with a browser to Claude.ai account.

### ISSUE THREAD

**Issue by colin4k** [Amm1rr/WebAI-to-API#35]
I had set cookie value in the 'Config.conf', but it still failed.

> INFO:root:claude_routes.py
> INFO:root:gemini_routes.py
> INFO:root:v1_routes.py
> INFO:root:http_routes.py
> INFO:root:http_routes.py.initialize_cookies
> INFO:root:utility.py./getCookie_Claude
> {'Error': "You should set 'COOKIE' in 'Config.conf' file for the Claude or login with a browser to Claude.ai account."}
> INFO:root:utility.py./getCookie_Gemini
> Traceback (most recent call last):
>   File "/home/colin/workspace/WebAI-to-API/webai2api/webai2api/utils/utility.py", line 118, in getCookie_Gemini
>     cookie = get_cookiestring("Google")
>   File "/home/colin/workspace/WebAI-to-API/webai2api/webai2api/utils/utility.py", line 66, in get_cookiestring
>     domain = domains[service_name]
> KeyError: 'Google'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/colin/workspace/WebAI-to-API/webai2api/run.py", line 3, in <module>
>     from webai2api.__main__ import app
>   File "/home/colin/workspace/WebAI-to-API/webai2api/webai2api/__main__.py", line 5, in <module>
>     from .routes.http_routes import web_ui_middleware
>   File "/home/colin/workspace/WebAI-to-API/webai2api/webai2api/routes/http_routes.py", line 32, in <module>
>     initialize_cookies()
>   File "/home/colin/workspace/WebAI-to-API/webai2api/webai2api/routes/http_routes.py", line 27, in initialize_cookies
>     COOKIE_GEMINI = utility.getCookie_Gemini()
>   File "/home/colin/workspace/WebAI-to-API/webai2api/webai2api/utils/utility.py", line 127, in getCookie_Gemini
>     cookies = browser_cookie3.load(domain_name=domain)
>   File "/home/colin/anaconda3/envs/claude/lib/python3.10/site-packages/browser_cookie3/__init__.py", line 1233, in load
>     for cookie in cookie_fn(domain_name=domain_name):
>   File "/home/colin/anaconda3/envs/claude/lib/python3.10/site-packages/browser_cookie3/__init__.py", line 1160, in chrome
>     return Chrome(cookie_file, domain_name, key_file).load()
>   File "/home/colin/anaconda3/envs/claude/lib/python3.10/site-packages/browser_cookie3/__init__.py", line 626, in __init__
>     super().__init__(browser='Chrome', cookie_file=cookie_file,
>   File "/home/colin/anaconda3/envs/claude/lib/python3.10/site-packages/browser_cookie3/__init__.py", line 416, in __init__
>     self.__add_key_and_cookie_file(**kwargs)
>   File "/home/colin/anaconda3/envs/claude/lib/python3.10/site-packages/browser_cookie3/__init__.py", line 431, in __add_key_and_cookie_file
>     USE_DBUS_LINUX).get_password(os_crypt_name)
>   File "/home/colin/anaconda3/envs/claude/lib/python3.10/site-packages/browser_cookie3/__init__.py", line 232, in get_password
>     return self.__get_secretstorage_password(os_crypt_name)
>   File "/home/colin/anaconda3/envs/claude/lib/python3.10/site-packages/browser_cookie3/__init__.py", line 247, in __get_secretstorage_password
>     return self.__methods_map.get('secretstorage')(schema, os_crypt_name)
>   File "/home/colin/anaconda3/envs/claude/lib/python3.10/site-packages/browser_cookie3/__init__.py", line 303, in __get_secretstorage_item_jeepney
>     with _JeepneyConnection(*args) as connection:
>   File "/home/colin/anaconda3/envs/claude/lib/python3.10/site-packages/browser_cookie3/__init__.py", line 195, in __enter__
>     self.__connection = open_dbus_connection()
>   File "/home/colin/anaconda3/envs/claude/lib/python3.10/site-packages/jeepney/io/blocking.py", line 342, in open_dbus_connection
>     sock = prep_socket(bus_addr, enable_fds, timeout=auth_timeout)
>   File "/home/colin/anaconda3/envs/claude/lib/python3.10/site-packages/jeepney/io/blocking.py", line 310, in prep_socket
>     with_sock_deadline(sock.connect, addr)
>   File "/home/colin/anaconda3/envs/claude/lib/python3.10/site-packages/jeepney/io/blocking.py", line 307, in with_sock_deadline
>     return meth(*args)
> FileNotFoundError: [Errno 2] No such file or directory

**Comment by VariantConst** [comment]
have the same problem

**Comment by kairushinjuu** [comment]
me too, it seems the claude session cookies have changed format

**Comment by Amm1rr** [comment]
Hmm, interesting.

Actually, I found a bug here. The script never uses the config.conf file. It's always trying to load by the web browser session, but it's working.

Could you check your sessions at http://localhost:8000/WebAI?

Can you see sessions for Claude and Gemini?

**Comment by badunch** [comment]
There is a way to authenticate using a config file.  if you look in the utils/utility.py file. You will see     

gemini_session_names = {
        "bardts": "__Secure-1PSIDTS",
        "bardcc": "__Secure-1PSIDCC"
    }
    default_gemini_session_name = "__Secure-1PSID"
    
I am assuming those would be the values you would be from the session. Which you can find under the Ppplication tap of the developer options on chrome. Under cookies.  Try to authenticate manually?

**Comment by bejokun** [comment]
same here, like to many bugs not clean coding. hope have func to choose gemini or claude or openai
